---
version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - dependencies
      - devops
    commit-message:
      prefix: 'chore(gh-actions): '
    groups:
      gh-actions:
        patterns:
          - '*'
