---
name: PR review reminder

# yamllint disable-line rule:truthy
on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  pull-request-review-reminder:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: tommykw/pull-request-reviewer-reminder-action@v2
        with:
          github_token: ${{ secrets.token }}
          # yamllint disable-line rule:line-length
          reminder_message: Para cada dia que esta PR não é revisada, um gatinho é brutalmente assasinado.
            Não deixe gatinhos morrer em vão 😭, revise a PR! 🐱
          review_turnaround_hours: 24
