---
name: PR

# yamllint disable-line rule:truthy
on:
  workflow_call:

concurrency:
  group: pr-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  assignee:
    name: Ensure Assignee
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    if: ${{ github.event.action == 'opened' || github.event.action == 'ready_for_review' }}
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.actor }}
          github-token: ${{ github.token }}
  triage:
    name: Triage Labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ github.token }}
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - uses: beemojs/conventional-pr-action@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          config-preset: angular
