---
name: Test App

# yamllint disable-line rule:truthy
on:
  workflow_call:
    inputs:
      check-paths:
        type: string
        default: frontend
      working-directory:
        type: string
        default: frontend
      node-version:
        type: number
        default: 20
      core-lint:
        type: boolean
        default: true

concurrency:
  group: tests-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check-changes:
    name: Check Changes
    runs-on: ubuntu-latest
    outputs:
      has-changes: ${{ steps.check.outputs.changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 100
      - uses: marceloprado/has-changed-path@v1.0.1
        id: check
        with:
          paths: ${{ inputs.check-paths }}
  test:
    name: Test App
    needs: check-changes
    if: ${{ needs.check-changes.outputs.has-changes == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v4
      - id: setup-node
        name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: yarn
          cache-dependency-path: '**/yarn.lock'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"
      - name: Yarn cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            "**/node_modules"
          # yamllint disable-line rule:line-length
          key: node-modules-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-${{ hashFiles('**/yarn.lock')
            }}
          restore-keys: |
            node-modules-${{ runner.os }}-${{ steps.setup-node.outputs.node-version }}-
            node-modules-${{ runner.os }}-
      - name: Yarn install
        run: yarn install --immutable
      - name: App lint
        run: yarn app-lint
